main: buttondevteam.presents.ButtonPresents
name: ButtonPresents
version: 0.0.1

commands:
  dictionary:
    description: A set of Hello World commands and listeners, type in /hello to see subcommands
  rtp:
    description: A command that allows players to randomly teleport across the map
  spawn:
    description: A set of commands designed to be used in spawn
  magic:
    description: A set of fun commands designed for cheaty stuff
  research:
    description: A set of commands designed for R and D